# ----
# Site

title: Gram Up!
url: "https://gramup.me"
baseurl:
google_analytics_key: UA-137776639-1
yandex_metrica: 53083903
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Get free likes, double your followers and start earning with your Instagram
keywords: instabot, instagram bot, python, gramup, gram up, free instagram likes
author:
  name: Daniil Okhlopkov
  email: 
  twitter: # twitter username without the @ symbol
social:
  name: Gram Up!
  links:
    - https://get.gramup.me
    - https://github.com/instagrambot/gramup


# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "home.html"
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "onepager"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
